# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [49]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [50]:
A = np.arange(1, 16).reshape(3,5)

In [51]:
print("Matrix A:")
print(A)
print("Number of axes (ndim):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Number of axes (ndim): 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [52]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [53]:
# Elementwise subtraction
print("Elementwise subtraction:")
print(B - C)
print()

# Elementwise multiplication
print("Elementwise multiplication:")
print(B * C)
print()

# Matrix multiplication
print("Matrix multiplication:")
print(B @ C)
print()


Elementwise subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]



### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [54]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
# Exponentiate each number elementwise
print("Exponentiated (np.exp):")
print(np.exp(D))
print()

# Minimum value in the whole matrix
print("Minimum value in D:", np.min(D))

# Minimum value in each row
print("Minimum value in each row:", np.min(D, axis=1))

# Minimum value in each column
print("Minimum value in each column:", np.min(D, axis=0))

# Index of minimum value in the whole matrix
print("Index of minimum value in D (flattened):", np.argmin(D))

# Index of minimum value in each row
print("Index of minimum value in each row:", np.argmin(D, axis=1))

# Sum for all elements
print("Sum of all elements:", np.sum(D))

# Mean for each column
print("Mean for each column:", np.mean(D, axis=0))

# Median for each column
print("Median for each column:", np.median(D, axis=0))

Exponentiated (np.exp):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in D: 1
Minimum value in each row: [1 4 7]
Minimum value in each column: [1 2 3]
Index of minimum value in D (flattened): 0
Index of minimum value in each row: [0 0 0]
Sum of all elements: 45
Mean for each column: [4. 5. 6.]
Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [56]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [57]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Man får en del-array som motsvarar de återstående axlarna. I exemplet A[1], returnerar A[1] hela den andra raden som en 1D-array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [58]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [60]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [61]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [62]:
# Koden skapar först en array a med 30 element och sedan omformar den till en 3D-array b med form (2, 3, 5):
# Den första axeln har 2 blocks
# Den andra axeln har 3 rader per block
# Den tredje axeln har 5 kolumner per rad

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [63]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [64]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [65]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [66]:
def add_mult_matrices(mat1, mat2, operation):
    import numpy as np

    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Inputs must be numpy arrays.")

    if operation == 'add':
        if mat1.shape != mat2.shape:
            raise ValueError("Shapes must match for addition.")
        return mat1 + mat2

    elif operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError("Shapes not aligned for multiplication.")
        return mat1 @ mat2

    else:
        raise ValueError("Operation must be 'add' or 'multiply'.")

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [67]:
# Uppgift 10.1.1

x = np.array([4, 3])

# (a) x dimensions
print("Dimension of x:", x.shape)

# (b) Beräkna 5x
x5 = 5 * x
print(x5)

# (c) Beräkna 3x
x3 = 3 * x
print(x3)

# (d) Beräkna 5x + 3x med add_mult_matrices
sum_x5_x3 = add_mult_matrices(x5, x3, 'add')
print(sum_x5_x3)

# (e) Beräkna 8x
x8 = 8 * x
print(x8)

# (f) Beräkna 4x - x med add_mult_matrices
x4 = 4 * x
diff_x4_x1 = add_mult_matrices(x4, -x, 'add')
print(diff_x4_x1)

# (g) Beräkna xᵀ
x_T = x.T
print(x_T)
print("Dimension efter transponering:", x_T.shape)

# (h) Är x + xᵀ definierat?
# Nej, eftersom x är en kolonnvektor och xᵀ är en radvektor.

# (i) Beräkna ||x||
norm_x = np.linalg.norm(x)
print("||x|| =", norm_x)

# Uppgift 10.1.2

# Definiera vektorn v
v = np.array([3, 7, 0, 11])
print(v)

# (a) v dimensions
print("Dimension of v:", v.shape)

# (b) Beräkna 2v
v2 = 2 * v
print(v2)

# (c) Beräkna 5v + 2v med add_mult_matrices
sum_v5_v2 = add_mult_matrices(5 * v, 2 * v, 'add')
print(sum_v5_v2)

# (d) Beräkna 4v - 2v med add_mult_matrices
diff_v4_v2 = add_mult_matrices(4 * v, -2 * v, 'add')
print(diff_v4_v2)

# (e) Beräkna vᵀ
v_T = v.T
print(v_T)
print("Dimension efter transponering:", v_T.shape)

# (f) beräkna ||v||
norm_v = np.linalg.norm(v)
print("||v|| =", norm_v)

# Uppgift 10.1.3
# Definiera v1 och v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# beräkna ||v1||
norm_v1 = np.linalg.norm(v1)
print("||v1|| =", norm_v1)

# beräkna ||v1 - v2||
norm_diff_v1_v2 = np.linalg.norm(v1 - v2)
print("||v1 - v2|| =", norm_diff_v1_v2)

Dimension of x: (2,)
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
[4 3]
Dimension efter transponering: (2,)
||x|| = 5.0
[ 3  7  0 11]
Dimension of v: (4,)
[ 6 14  0 22]
[21 49  0 77]
[ 6 14  0 22]
[ 3  7  0 11]
Dimension efter transponering: (4,)
||v|| = 13.379088160259652
||v1|| = 7.14142842854285
||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [68]:
# Koefficientmatris A
A = np.array([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 3],
    [7, 1, 5]
])

# Högerledsvektor b
b = np.array([7, 4, 11, 9])

# verifiera lösningen Ax = b
x = np.array([1, 1, 1])  

print("A @ x =", A @ x)
print("b =", b)

A @ x = [ 9 13  8 13]
b = [ 7  4 11  9]


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [69]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [70]:
print("Före ändring:")
print("v1:", v1)
print("v2:", v2)

# Ändra sista elementet i v2
v2[-1] = 123

print("Efter ändring:")
print("v1:", v1)
print("v2:", v2)

# Ja, v2 är en vy av v1, så ändringar i v2 påverkar v1.

Före ändring:
v1: [0 1 2 3]
v2: [2 3]
Efter ändring:
v1: [  0   1   2 123]
v2: [  2 123]
